sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
script:
    - curl -Lo ~/.config/fish/functions/verman.fish --create-dirs git.io/verman
    - fish -c "echo 6.2.0 > .node-version; verman; node -v"
